// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diff.proto

package boa.types;

public final class Diff {
  private Diff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChangedFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .boa.types.ChangeKind change = 1;
    /**
     * <code>required .boa.types.ChangeKind change = 1;</code>
     */
    boolean hasChange();
    /**
     * <code>required .boa.types.ChangeKind change = 1;</code>
     */
    boa.types.Shared.ChangeKind getChange();

    // required .boa.types.ChangedFile.FileKind kind = 2;
    /**
     * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
     */
    boolean hasKind();
    /**
     * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
     */
    boa.types.Diff.ChangedFile.FileKind getKind();

    // required string name = 3;
    /**
     * <code>required string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string key = 4;
    /**
     * <code>required string key = 4;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 4;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 4;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // optional .boa.types.ASTRoot ast = 5;
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    boolean hasAst();
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    boa.types.Ast.ASTRoot getAst();
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    boa.types.Ast.ASTRootOrBuilder getAstOrBuilder();

    // optional .boa.types.CommentsRoot comments = 6;
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    boolean hasComments();
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    boa.types.Ast.CommentsRoot getComments();
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    boa.types.Ast.CommentsRootOrBuilder getCommentsOrBuilder();
  }
  /**
   * Protobuf type {@code boa.types.ChangedFile}
   */
  public static final class ChangedFile extends
      com.google.protobuf.GeneratedMessage
      implements ChangedFileOrBuilder {
    // Use ChangedFile.newBuilder() to construct.
    private ChangedFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangedFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangedFile defaultInstance;
    public static ChangedFile getDefaultInstance() {
      return defaultInstance;
    }

    public ChangedFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangedFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              boa.types.Shared.ChangeKind value = boa.types.Shared.ChangeKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                change_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              boa.types.Diff.ChangedFile.FileKind value = boa.types.Diff.ChangedFile.FileKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                kind_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              key_ = input.readBytes();
              break;
            }
            case 42: {
              boa.types.Ast.ASTRoot.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = ast_.toBuilder();
              }
              ast_ = input.readMessage(boa.types.Ast.ASTRoot.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ast_);
                ast_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              boa.types.Ast.CommentsRoot.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = comments_.toBuilder();
              }
              comments_ = input.readMessage(boa.types.Ast.CommentsRoot.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(comments_);
                comments_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return boa.types.Diff.internal_static_boa_types_ChangedFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return boa.types.Diff.internal_static_boa_types_ChangedFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              boa.types.Diff.ChangedFile.class, boa.types.Diff.ChangedFile.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangedFile> PARSER =
        new com.google.protobuf.AbstractParser<ChangedFile>() {
      public ChangedFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangedFile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangedFile> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code boa.types.ChangedFile.FileKind}
     */
    public enum FileKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 1;</code>
       */
      UNKNOWN(0, 1),
      /**
       * <code>BINARY = 2;</code>
       */
      BINARY(1, 2),
      /**
       * <code>TEXT = 3;</code>
       */
      TEXT(2, 3),
      /**
       * <code>XML = 4;</code>
       */
      XML(3, 4),
      /**
       * <code>SOURCE_JAVA_ERROR = 5;</code>
       */
      SOURCE_JAVA_ERROR(4, 5),
      /**
       * <code>SOURCE_JAVA_JLS2 = 6;</code>
       */
      SOURCE_JAVA_JLS2(5, 6),
      /**
       * <code>SOURCE_JAVA_JLS3 = 7;</code>
       */
      SOURCE_JAVA_JLS3(6, 7),
      /**
       * <code>SOURCE_JAVA_JLS4 = 8;</code>
       */
      SOURCE_JAVA_JLS4(7, 8),
      ;

      /**
       * <code>UNKNOWN = 1;</code>
       */
      public static final int UNKNOWN_VALUE = 1;
      /**
       * <code>BINARY = 2;</code>
       */
      public static final int BINARY_VALUE = 2;
      /**
       * <code>TEXT = 3;</code>
       */
      public static final int TEXT_VALUE = 3;
      /**
       * <code>XML = 4;</code>
       */
      public static final int XML_VALUE = 4;
      /**
       * <code>SOURCE_JAVA_ERROR = 5;</code>
       */
      public static final int SOURCE_JAVA_ERROR_VALUE = 5;
      /**
       * <code>SOURCE_JAVA_JLS2 = 6;</code>
       */
      public static final int SOURCE_JAVA_JLS2_VALUE = 6;
      /**
       * <code>SOURCE_JAVA_JLS3 = 7;</code>
       */
      public static final int SOURCE_JAVA_JLS3_VALUE = 7;
      /**
       * <code>SOURCE_JAVA_JLS4 = 8;</code>
       */
      public static final int SOURCE_JAVA_JLS4_VALUE = 8;


      public final int getNumber() { return value; }

      public static FileKind valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN;
          case 2: return BINARY;
          case 3: return TEXT;
          case 4: return XML;
          case 5: return SOURCE_JAVA_ERROR;
          case 6: return SOURCE_JAVA_JLS2;
          case 7: return SOURCE_JAVA_JLS3;
          case 8: return SOURCE_JAVA_JLS4;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FileKind>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileKind>() {
              public FileKind findValueByNumber(int number) {
                return FileKind.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return boa.types.Diff.ChangedFile.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileKind[] VALUES = values();

      public static FileKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FileKind(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:boa.types.ChangedFile.FileKind)
    }

    private int bitField0_;
    // required .boa.types.ChangeKind change = 1;
    public static final int CHANGE_FIELD_NUMBER = 1;
    private boa.types.Shared.ChangeKind change_;
    /**
     * <code>required .boa.types.ChangeKind change = 1;</code>
     */
    public boolean hasChange() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .boa.types.ChangeKind change = 1;</code>
     */
    public boa.types.Shared.ChangeKind getChange() {
      return change_;
    }

    // required .boa.types.ChangedFile.FileKind kind = 2;
    public static final int KIND_FIELD_NUMBER = 2;
    private boa.types.Diff.ChangedFile.FileKind kind_;
    /**
     * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
     */
    public boa.types.Diff.ChangedFile.FileKind getKind() {
      return kind_;
    }

    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>required string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string key = 4;
    public static final int KEY_FIELD_NUMBER = 4;
    private java.lang.Object key_;
    /**
     * <code>required string key = 4;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string key = 4;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 4;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .boa.types.ASTRoot ast = 5;
    public static final int AST_FIELD_NUMBER = 5;
    private boa.types.Ast.ASTRoot ast_;
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    public boolean hasAst() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    public boa.types.Ast.ASTRoot getAst() {
      return ast_;
    }
    /**
     * <code>optional .boa.types.ASTRoot ast = 5;</code>
     */
    public boa.types.Ast.ASTRootOrBuilder getAstOrBuilder() {
      return ast_;
    }

    // optional .boa.types.CommentsRoot comments = 6;
    public static final int COMMENTS_FIELD_NUMBER = 6;
    private boa.types.Ast.CommentsRoot comments_;
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    public boa.types.Ast.CommentsRoot getComments() {
      return comments_;
    }
    /**
     * <code>optional .boa.types.CommentsRoot comments = 6;</code>
     */
    public boa.types.Ast.CommentsRootOrBuilder getCommentsOrBuilder() {
      return comments_;
    }

    private void initFields() {
      change_ = boa.types.Shared.ChangeKind.ADDED;
      kind_ = boa.types.Diff.ChangedFile.FileKind.UNKNOWN;
      name_ = "";
      key_ = "";
      ast_ = boa.types.Ast.ASTRoot.getDefaultInstance();
      comments_ = boa.types.Ast.CommentsRoot.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAst()) {
        if (!getAst().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasComments()) {
        if (!getComments().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, change_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, ast_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, comments_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, change_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, ast_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, comments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static boa.types.Diff.ChangedFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Diff.ChangedFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Diff.ChangedFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Diff.ChangedFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Diff.ChangedFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Diff.ChangedFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static boa.types.Diff.ChangedFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static boa.types.Diff.ChangedFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static boa.types.Diff.ChangedFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Diff.ChangedFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(boa.types.Diff.ChangedFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.types.ChangedFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements boa.types.Diff.ChangedFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return boa.types.Diff.internal_static_boa_types_ChangedFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return boa.types.Diff.internal_static_boa_types_ChangedFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                boa.types.Diff.ChangedFile.class, boa.types.Diff.ChangedFile.Builder.class);
      }

      // Construct using boa.types.Diff.ChangedFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAstFieldBuilder();
          getCommentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        change_ = boa.types.Shared.ChangeKind.ADDED;
        bitField0_ = (bitField0_ & ~0x00000001);
        kind_ = boa.types.Diff.ChangedFile.FileKind.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (astBuilder_ == null) {
          ast_ = boa.types.Ast.ASTRoot.getDefaultInstance();
        } else {
          astBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (commentsBuilder_ == null) {
          comments_ = boa.types.Ast.CommentsRoot.getDefaultInstance();
        } else {
          commentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return boa.types.Diff.internal_static_boa_types_ChangedFile_descriptor;
      }

      public boa.types.Diff.ChangedFile getDefaultInstanceForType() {
        return boa.types.Diff.ChangedFile.getDefaultInstance();
      }

      public boa.types.Diff.ChangedFile build() {
        boa.types.Diff.ChangedFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public boa.types.Diff.ChangedFile buildPartial() {
        boa.types.Diff.ChangedFile result = new boa.types.Diff.ChangedFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.change_ = change_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (astBuilder_ == null) {
          result.ast_ = ast_;
        } else {
          result.ast_ = astBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (commentsBuilder_ == null) {
          result.comments_ = comments_;
        } else {
          result.comments_ = commentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof boa.types.Diff.ChangedFile) {
          return mergeFrom((boa.types.Diff.ChangedFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(boa.types.Diff.ChangedFile other) {
        if (other == boa.types.Diff.ChangedFile.getDefaultInstance()) return this;
        if (other.hasChange()) {
          setChange(other.getChange());
        }
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000008;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasAst()) {
          mergeAst(other.getAst());
        }
        if (other.hasComments()) {
          mergeComments(other.getComments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChange()) {
          
          return false;
        }
        if (!hasKind()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasKey()) {
          
          return false;
        }
        if (hasAst()) {
          if (!getAst().isInitialized()) {
            
            return false;
          }
        }
        if (hasComments()) {
          if (!getComments().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        boa.types.Diff.ChangedFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (boa.types.Diff.ChangedFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .boa.types.ChangeKind change = 1;
      private boa.types.Shared.ChangeKind change_ = boa.types.Shared.ChangeKind.ADDED;
      /**
       * <code>required .boa.types.ChangeKind change = 1;</code>
       */
      public boolean hasChange() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .boa.types.ChangeKind change = 1;</code>
       */
      public boa.types.Shared.ChangeKind getChange() {
        return change_;
      }
      /**
       * <code>required .boa.types.ChangeKind change = 1;</code>
       */
      public Builder setChange(boa.types.Shared.ChangeKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .boa.types.ChangeKind change = 1;</code>
       */
      public Builder clearChange() {
        bitField0_ = (bitField0_ & ~0x00000001);
        change_ = boa.types.Shared.ChangeKind.ADDED;
        onChanged();
        return this;
      }

      // required .boa.types.ChangedFile.FileKind kind = 2;
      private boa.types.Diff.ChangedFile.FileKind kind_ = boa.types.Diff.ChangedFile.FileKind.UNKNOWN;
      /**
       * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
       */
      public boa.types.Diff.ChangedFile.FileKind getKind() {
        return kind_;
      }
      /**
       * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
       */
      public Builder setKind(boa.types.Diff.ChangedFile.FileKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .boa.types.ChangedFile.FileKind kind = 2;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kind_ = boa.types.Diff.ChangedFile.FileKind.UNKNOWN;
        onChanged();
        return this;
      }

      // required string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // required string key = 4;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 4;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string key = 4;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 4;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 4;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 4;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 4;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }

      // optional .boa.types.ASTRoot ast = 5;
      private boa.types.Ast.ASTRoot ast_ = boa.types.Ast.ASTRoot.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          boa.types.Ast.ASTRoot, boa.types.Ast.ASTRoot.Builder, boa.types.Ast.ASTRootOrBuilder> astBuilder_;
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public boolean hasAst() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public boa.types.Ast.ASTRoot getAst() {
        if (astBuilder_ == null) {
          return ast_;
        } else {
          return astBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public Builder setAst(boa.types.Ast.ASTRoot value) {
        if (astBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ast_ = value;
          onChanged();
        } else {
          astBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public Builder setAst(
          boa.types.Ast.ASTRoot.Builder builderForValue) {
        if (astBuilder_ == null) {
          ast_ = builderForValue.build();
          onChanged();
        } else {
          astBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public Builder mergeAst(boa.types.Ast.ASTRoot value) {
        if (astBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              ast_ != boa.types.Ast.ASTRoot.getDefaultInstance()) {
            ast_ =
              boa.types.Ast.ASTRoot.newBuilder(ast_).mergeFrom(value).buildPartial();
          } else {
            ast_ = value;
          }
          onChanged();
        } else {
          astBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public Builder clearAst() {
        if (astBuilder_ == null) {
          ast_ = boa.types.Ast.ASTRoot.getDefaultInstance();
          onChanged();
        } else {
          astBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public boa.types.Ast.ASTRoot.Builder getAstBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getAstFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      public boa.types.Ast.ASTRootOrBuilder getAstOrBuilder() {
        if (astBuilder_ != null) {
          return astBuilder_.getMessageOrBuilder();
        } else {
          return ast_;
        }
      }
      /**
       * <code>optional .boa.types.ASTRoot ast = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          boa.types.Ast.ASTRoot, boa.types.Ast.ASTRoot.Builder, boa.types.Ast.ASTRootOrBuilder> 
          getAstFieldBuilder() {
        if (astBuilder_ == null) {
          astBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              boa.types.Ast.ASTRoot, boa.types.Ast.ASTRoot.Builder, boa.types.Ast.ASTRootOrBuilder>(
                  ast_,
                  getParentForChildren(),
                  isClean());
          ast_ = null;
        }
        return astBuilder_;
      }

      // optional .boa.types.CommentsRoot comments = 6;
      private boa.types.Ast.CommentsRoot comments_ = boa.types.Ast.CommentsRoot.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          boa.types.Ast.CommentsRoot, boa.types.Ast.CommentsRoot.Builder, boa.types.Ast.CommentsRootOrBuilder> commentsBuilder_;
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public boolean hasComments() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public boa.types.Ast.CommentsRoot getComments() {
        if (commentsBuilder_ == null) {
          return comments_;
        } else {
          return commentsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public Builder setComments(boa.types.Ast.CommentsRoot value) {
        if (commentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          comments_ = value;
          onChanged();
        } else {
          commentsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public Builder setComments(
          boa.types.Ast.CommentsRoot.Builder builderForValue) {
        if (commentsBuilder_ == null) {
          comments_ = builderForValue.build();
          onChanged();
        } else {
          commentsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public Builder mergeComments(boa.types.Ast.CommentsRoot value) {
        if (commentsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              comments_ != boa.types.Ast.CommentsRoot.getDefaultInstance()) {
            comments_ =
              boa.types.Ast.CommentsRoot.newBuilder(comments_).mergeFrom(value).buildPartial();
          } else {
            comments_ = value;
          }
          onChanged();
        } else {
          commentsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public Builder clearComments() {
        if (commentsBuilder_ == null) {
          comments_ = boa.types.Ast.CommentsRoot.getDefaultInstance();
          onChanged();
        } else {
          commentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public boa.types.Ast.CommentsRoot.Builder getCommentsBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getCommentsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      public boa.types.Ast.CommentsRootOrBuilder getCommentsOrBuilder() {
        if (commentsBuilder_ != null) {
          return commentsBuilder_.getMessageOrBuilder();
        } else {
          return comments_;
        }
      }
      /**
       * <code>optional .boa.types.CommentsRoot comments = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          boa.types.Ast.CommentsRoot, boa.types.Ast.CommentsRoot.Builder, boa.types.Ast.CommentsRootOrBuilder> 
          getCommentsFieldBuilder() {
        if (commentsBuilder_ == null) {
          commentsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              boa.types.Ast.CommentsRoot, boa.types.Ast.CommentsRoot.Builder, boa.types.Ast.CommentsRootOrBuilder>(
                  comments_,
                  getParentForChildren(),
                  isClean());
          comments_ = null;
        }
        return commentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:boa.types.ChangedFile)
    }

    static {
      defaultInstance = new ChangedFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.types.ChangedFile)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_types_ChangedFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_types_ChangedFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndiff.proto\022\tboa.types\032\014shared.proto\032\ta" +
      "st.proto\"\334\002\n\013ChangedFile\022%\n\006change\030\001 \002(\016" +
      "2\025.boa.types.ChangeKind\022-\n\004kind\030\002 \002(\0162\037." +
      "boa.types.ChangedFile.FileKind\022\014\n\004name\030\003" +
      " \002(\t\022\013\n\003key\030\004 \002(\t\022\037\n\003ast\030\005 \001(\0132\022.boa.typ" +
      "es.ASTRoot\022)\n\010comments\030\006 \001(\0132\027.boa.types" +
      ".CommentsRoot\"\217\001\n\010FileKind\022\013\n\007UNKNOWN\020\001\022" +
      "\n\n\006BINARY\020\002\022\010\n\004TEXT\020\003\022\007\n\003XML\020\004\022\025\n\021SOURCE" +
      "_JAVA_ERROR\020\005\022\024\n\020SOURCE_JAVA_JLS2\020\006\022\024\n\020S" +
      "OURCE_JAVA_JLS3\020\007\022\024\n\020SOURCE_JAVA_JLS4\020\010B",
      "\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_boa_types_ChangedFile_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_boa_types_ChangedFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_types_ChangedFile_descriptor,
              new java.lang.String[] { "Change", "Kind", "Name", "Key", "Ast", "Comments", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          boa.types.Shared.getDescriptor(),
          boa.types.Ast.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
